# Generated by Django 3.2.5 on 2021-08-16 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210816_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id_first_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='id_second_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
