# Generated by Django 3.2.5 on 2021-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20210808_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
