# Generated by Django 3.2.5 on 2021-08-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
