# Generated by Django 3.2.5 on 2021-08-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_auto_20210814_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
