# Generated by Django 3.2.5 on 2021-08-19 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0013_alter_bb_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bb_id',
            new_name='bboard',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bb',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Цена'),
        ),
    ]
